### ISSUE TITLE
ImportError: cannot import name '_wraps' from 'jax._src.numpy.util'

### ISSUE THREAD

**Issue by kentoabeywardane** [chrisflesher/jax-scipy-spatial#6]
Hello,

I am getting the above ImportError. A recent commit to jax or jaxlib [renamed "_wraps" to "implements" ](https://github.com/google/jax/commit/43a9faa06a1dcbd993dd224d55d1d3efa3346eda) in the jax._src.numpy.util module.

Versions:
Jax==0.4.25 (cpu)
jaxlib==0.4.25
jax_scipy_spatial==0.2.1

Hope this helps!

**Comment by chrisflesher** [comment]
Ok, hopefully should be fixed now?

**Comment by kentoabeywardane** [comment]
Thanks for the quick fix, but it seems like only the `transform` module was fixed, but the problem still persists in `distance` module.

Also thanks for the great package!

**Comment by chrisflesher** [comment]
Added these, hopefully it is fixed this now (in version 0.2.3).
